# 建议补充到 translation_utils.py 的 TEAM_MAP：
TEAM_MAP.update({
    "Accra Lions": "请填写中文",
    "Akhmat": "请填写中文",
    "Al Kholood": "请填写中文",
    "Al Najma": "请填写中文",
    "Al Okhdood": "请填写中文",
    "Al Orubah": "请填写中文",
    "Al Quwa Al Jawiya": "请填写中文",
    "Al Riffa": "请填写中文",
    "Al Zulfi": "请填写中文",
    "Al-Karma": "请填写中文",
    "Al-Qasim": "请填写中文",
    "Al-Raed": "请填写中文",
    "Atlas U21": "请填写中文",
    "BST Galaxy": "请填写中文",
    "Baghdad": "请填写中文",
    "Başakşehir": "请填写中文",
    "Boluspor": "请填写中文",
    "Congleton Town": "请填写中文",
    "Cruz Azul U21": "请填写中文",
    "Duhok": "请填写中文",
    "Entebbe UPPC": "请填写中文",
    "Erbil": "请填写中文",
    "Falcons": "请填写中文",
    "Fleetwood Town U21": "请填写中文",
    "Fortaleza U20": "请填写中文",
    "Fortuna Köln": "请填写中文",
    "Fortune": "请填写中文",
    "Gazişehir Gaziantep": "请填写中文",
    "Gendrim": "请填写中文",
    "Grazer AK": "请填写中文",
    "HNK Gorica": "请填写中文",
    "Hawks": "请填写中文",
    "Independente-AP U20": "请填写中文",
    "Ituano U20": "请填写中文",
    "Jeddah Club": "请填写中文",
    "Juventus U20": "请填写中文",
    "Kelantan United": "请填写中文",
    "Kocaelispor": "请填写中文",
    "Komárno": "请填写中文",
    "Medina United": "请填写中文",
    "Monterrey U21": "请填写中文",
    "NK Osijek": "请填写中文",
    "NK Slaven Belupo": "请填写中文",
    "Nacional SP U20": "请填写中文",
    "Necaxa U21": "请填写中文",
    "Novi Pazar": "请填写中文",
    "Novorizontino U20": "请填写中文",
    "Operário PR U20": "请填写中文",
    "Peterborough United U21": "请填写中文",
    "Petro de Luanda": "请填写中文",
    "Police": "请填写中文",
    "Port City": "请填写中文",
    "Puebla U21": "请填写中文",
    "Radomlje": "请填写中文",
    "Sabah FA": "请填写中文",
    "TMT": "请填写中文",
    "Terengganu": "请填写中文",
    "Torreense U23": "请填写中文",
    "URA": "请填写中文",
    "Vukovar": "请填写中文",
    "Widnes": "请填写中文",
    "Wigan Athletic U21": "请填写中文",
    "Água Santa U20": "请填写中文",
})
