# 建议补充到 translation_utils.py 的 COUNTRY_MAP：
COUNTRY_MAP.update({
    "Algeria": "请填写中文",
    "Angola": "请填写中文",
    "Bahrain": "请填写中文",
    "Belgium": "请填写中文",
    "Brazil": "请填写中文",
    "England": "请填写中文",
    "France": "请填写中文",
    "Gambia": "请填写中文",
    "Germany": "请填写中文",
    "Ghana": "请填写中文",
    "Iraq": "请填写中文",
    "Israel": "请填写中文",
    "Italy": "请填写中文",
    "Malaysia": "请填写中文",
    "Mauritania": "请填写中文",
    "Mexico": "请填写中文",
    "Netherlands": "请填写中文",
    "Northern-Ireland": "请填写中文",
    "Portugal": "请填写中文",
    "Saudi-Arabia": "请填写中文",
    "Scotland": "请填写中文",
    "Spain": "请填写中文",
    "Turkey": "请填写中文",
    "Uganda": "请填写中文",
    "Wales": "请填写中文",
    "World": "请填写中文",
})
