# 建议补充到 translation_utils.py 的 CITY_MAP：
CITY_MAP.update({
    "Abha": "请填写中文",
    "Al-Ahsa": "请填写中文",
    "Arbil": "请填写中文",
    "Arbroath": "请填写中文",
    "Ayr": "请填写中文",
    "Ballymena": "请填写中文",
    "Barry": "请填写中文",
    "Bath": "请填写中文",
    "Belfast": "请填写中文",
    "Beverley": "请填写中文",
    "Bolton": "请填写中文",
    "Bridgend": "请填写中文",
    "Bristol": "请填写中文",
    "Buraidah": "请填写中文",
    "Caen": "请填写中文",
    "Caernarfon": "请填写中文",
    "Cardiff (Caerdydd)": "请填写中文",
    "Carrickfergus": "请填写中文",
    "Charleroi": "请填写中文",
    "Cosmopolis": "请填写中文",
    "Doncaster": "请填写中文",
    "Dortmund": "请填写中文",
    "Eastleigh": "请填写中文",
    "Embu das Artes": "请填写中文",
    "Failand, Somerset": "请填写中文",
    "Fethiye": "请填写中文",
    "Flint": "请填写中文",
    "Gaziantep": "请填写中文",
    "Glasgow": "请填写中文",
    "Guaratingueta": "请填写中文",
    "Guarulhos": "请填写中文",
    "Halifax": "请填写中文",
    "Haverfordwest": "请填写中文",
    "Huddersfield": "请填写中文",
    "Huddersfield, West Yorkshire": "请填写中文",
    "Istanbul": "请填写中文",
    "Itaquaquecetuba": "请填写中文",
    "Jeddah": "请填写中文",
    "Kidderminster": "请填写中文",
    "Kota Bharu": "请填写中文",
    "La Coruña": "请填写中文",
    "Leon": "请填写中文",
    "Luanda": "请填写中文",
    "Lurgan": "请填写中文",
    "Luton": "请填写中文",
    "Madrid": "请填写中文",
    "Mainz": "请填写中文",
    "Mogi das Cruzes": "请填写中文",
    "Najran": "请填写中文",
    "Netanya": "请填写中文",
    "Newcastle upon Tyne": "请填写中文",
    "Oswestry": "请填写中文",
    "Paulinia": "请填写中文",
    "Perth": "请填写中文",
    "Rome": "请填写中文",
    "Sakakah": "请填写中文",
    "San Sebastian": "请填写中文",
    "Sao Paulo": "请填写中文",
    "Scunthorpe": "请填写中文",
    "Sogakope": "请填写中文",
    "Stirling": "请填写中文",
    "Stockport": "请填写中文",
    "Stuttgart": "请填写中文",
    "Tamworth": "请填写中文",
    "Terengganu": "请填写中文",
    "Tiete": "请填写中文",
    "Utrecht": "请填写中文",
    "Wigan, Lancashire": "请填写中文",
})
