# 建议补充到 translation_utils.py 的 STADIUM_MAP：
STADIUM_MAP.update({
    "Aggborough Stadium": "请填写中文",
    "Al Fateh Club Stadium": "请填写中文",
    "Al Raid Club Stadium": "请填写中文",
    "Al-Jouf University Stadium": "请填写中文",
    "Attis Arena": "请填写中文",
    "Ballymena Showgrounds": "请填写中文",
    "Basaksehir Fatih Terim Stadium": "请填写中文",
    "Bishop Burton College": "请填写中文",
    "Bosuilstadion": "请填写中文",
    "Cardiff International Sports Stadium": "请填写中文",
    "Christopher Park": "请填写中文",
    "DragonBet Stadium": "请填写中文",
    "Eco-Power Stadium": "请填写中文",
    "Edgeley Park": "请填写中文",
    "Essity Stadium": "请填写中文",
    "Estadio Alfredo Di Stéfano": "请填写中文",
    "Estadio Antonio Soares de Oliveira": "请填写中文",
    "Estadio Francisco Ribeiro Nogueira": "请填写中文",
    "Estadio Herminio Esposito": "请填写中文",
    "Estadio Ildeu Silvestre do Carmo": "请填写中文",
    "Estadio Jose Ferreira Alves": "请填写中文",
    "Estadio Municipal Luis Perissinotto": "请填写中文",
    "Estadio Professor Dario Rodrigues Leite": "请填写中文",
    "Estadio Reino de León": "请填写中文",
    "Estadio Riazor": "请填写中文",
    "Estadio Thelmo de Almeida": "请填写中文",
    "Estádio 11 de Novembro": "请填写中文",
    "Firhill Stadium": "请填写中文",
    "Forthbank Stadium": "请填写中文",
    "Franso Hariri Stadium": "请填写中文",
    "Gayfield Park": "请填写中文",
    "Go Goodwins Stadium": "请填写中文",
    "Hamz Stadium": "请填写中文",
    "Ibrachina Arena": "请填写中文",
    "Jenner Park": "请填写中文",
    "John Smit": "请填写中文",
    "Kalyon Stadyumu": "请填写中文",
    "Kenilworth Road": "请填写中文",
    "King Abdullah Sports City": "请填写中文",
    "Loughview Leisure Arena": "请填写中文",
    "MHP Arena": "请填写中文",
    "McDiarmid Park": "请填写中文",
    "Memorial Stadium": "请填写中文",
    "Mewa Arena": "请填写中文",
    "Millers Oils High Performance Complex": "请填写中文",
    "Mourneview Park": "请填写中文",
    "Netanya Stadium": "请填写中文",
    "Park Hall Stadium": "请填写中文",
    "Prince Abdullah al-Faisal Stadium": "请填写中文",
    "Prince Abdullah bin Jalawi Stadium": "请填写中文",
    "Prince Hathloul bin Abdul Aziz Sports City": "请填写中文",
    "Prince Sultan bin Abdul Aziz Stadium": "请填写中文",
    "Reale Arena": "请填写中文",
    "Robins High Performance Centre": "请填写中文",
    "Signal Iduna Park": "请填写中文",
    "Silverlake Stadium": "请填写中文",
    "Somerset Park": "请填写中文",
    "St James' Park": "请填写中文",
    "Stade Michel d'Ornano": "请填写中文",
    "Stade du Pays de Charleroi": "请填写中文",
    "Stadio Olimpico": "请填写中文",
    "Stadion Galgenwaard": "请填写中文",
    "Sultan Mizan Zainal Abidin Stadium": "请填写中文",
    "Sultan Mohammad IV Stadium": "请填写中文",
    "The BetMcLean Oval": "请填写中文",
    "The City Stadium": "请填写中文",
    "The Lamb Ground": "请填写中文",
    "The Ogi Bridge Meadow Stadium": "请填写中文",
    "The Shay": "请填写中文",
    "Toto Turner Stadium": "请填写中文",
    "Toughsheet Community Stadium": "请填写中文",
    "Twerton Park": "请填写中文",
    "WAFA Park": "请填写中文",
    "Wilgar Park": "请填写中文",
})
