# 建议补充到 translation_utils.py 的 ODDS_TYPE_MAP：
ODDS_TYPE_MAP.update({
    "1st Goal in Interval": "请填写中文",
    "1x2 (1st Half)": "请填写中文",
    "1x2 - 10 minutes": "请填写中文",
    "1x2 - 20 minutes": "请填写中文",
    "1x2 - 30 minutes": "请填写中文",
    "1x2 - 40 minutes": "请填写中文",
    "1x2 - 50 minutes": "请填写中文",
    "1x2 - 60 minutes": "请填写中文",
    "1x2 - 70 minutes": "请填写中文",
    "1x2 - 80 minutes": "请填写中文",
    "1x2 Extra Time": "请填写中文",
    "1x2 Extra Time (1st Half)": "请填写中文",
    "2nd Goal in Interval": "请填写中文",
    "3-Way Handicap": "请填写中文",
    "3rd Goal in Interval": "请填写中文",
    "4th Goal in Interval": "请填写中文",
    "5th Goal in Interval": "请填写中文",
    "6th Goal in Interval": "请填写中文",
    "7th Goal in Interval": "请填写中文",
    "Action In Next 1 Minutes": "请填写中文",
    "Anytime Goal Scorer": "请填写中文",
    "Asian Corners": "请填写中文",
    "Asian Handicap": "请填写中文",
    "Asian Handicap (1st Half)": "请填写中文",
    "Asian Handicap Converted Penalties": "请填写中文",
    "Asian Handicap Extra Time": "请填写中文",
    "Away 1st Goal in Interval": "请填写中文",
    "Away 2nd Goal in Interval": "请填写中文",
    "Away 3rd Goal in Interval": "请填写中文",
    "Away 4th Goal in Interval": "请填写中文",
    "Away Penalty Shootout": "请填写中文",
    "Away Team Clean Sheet": "请填写中文",
    "Away Team Goals": "请填写中文",
    "Away Team Score a Goal (2nd Half)": "请填写中文",
    "Away Team to Score in Both Halves": "请填写中文",
    "Away Total Converted Penalties": "请填写中文",
    "Away Total Shots": "请填写中文",
    "Away Total shots on goal": "请填写中文",
    "Both Teams To Score (1st Half)": "请填写中文",
    "Both Teams To Score (2nd Half)": "请填写中文",
    "Both Teams To Score (ET)": "请填写中文",
    "Both Teams to Score": "请填写中文",
    "Corners 1x2": "请填写中文",
    "Corners Asian Handicap (1st Half)": "请填写中文",
    "Corners European Handicap": "请填写中文",
    "Correct Score (1st Half)": "请填写中文",
    "Correct Score in Shootouts": "请填写中文",
    "Double Chance": "请填写中文",
    "Draw No Bet": "请填写中文",
    "European Handicap (1st Half)": "请填写中文",
    "Extra Time Asian Corners": "请填写中文",
    "Extra Time Asian Corners (1st Half)": "请填写中文",
    "Extra Time Double Result": "请填写中文",
    "Extra Time Over/Under Line": "请填写中文",
    "Extra Time Total Corners (3 Ways)": "请填写中文",
    "Extra Time Total Corners (3 Ways) (1st Half)": "请填写中文",
    "Final Score": "请填写中文",
    "First Action In Next 5 Minutes": "请填写中文",
    "Fulltime Result": "请填写中文",
    "Game Won After Penalties Shootout": "请填写中文",
    "Game Won In Extra Time": "请填写中文",
    "Goal Scorer": "请填写中文",
    "Goals Odd/Even": "请填写中文",
    "Half Time/Full Time": "请填写中文",
    "Home 1st Goal in Interval": "请填写中文",
    "Home 2nd Goal in Interval": "请填写中文",
    "Home 3rd Goal in Interval": "请填写中文",
    "Home 4th Goal in Interval": "请填写中文",
    "Home Penalty Shootout": "请填写中文",
    "Home Team  to Score in Both Halves": "请填写中文",
    "Home Team Clean Sheet": "请填写中文",
    "Home Team Goals": "请填写中文",
    "Home Team Score a Goal (2nd Half)": "请填写中文",
    "Home Total Converted Penalties": "请填写中文",
    "Home Total Shots": "请填写中文",
    "Home Total shots on goal": "请填写中文",
    "How many goals will Away Team score?": "请填写中文",
    "How many goals will Home Team score?": "请填写中文",
    "Last Corner": "请填写中文",
    "Last Penalty Score/Miss": "请填写中文",
    "Last Team to Score (3 way)": "请填写中文",
    "Match Corners": "请填写中文",
    "Match Goals": "请填写中文",
    "Method of 1st Goal": "请填写中文",
    "Method of 2nd Goal": "请填写中文",
    "Method of 3rd Goal": "请填写中文",
    "Method of 4th Goal": "请填写中文",
    "Method of Victory": "请填写中文",
    "Next 10 Minutes Total": "请填写中文",
    "Over/Under (1st Half)": "请填写中文",
    "Over/Under Extra Time": "请填写中文",
    "Over/Under Extra Time (1st Half)": "请填写中文",
    "Over/Under Line": "请填写中文",
    "Over/Under Line (1st Half)": "请填写中文",
    "Penalties Shootout Winner": "请填写中文",
    "Player Assists": "请填写中文",
    "Player Shots": "请填写中文",
    "Player Shots on Targets": "请填写中文",
    "Player to be Booked": "请填写中文",
    "Player to be Sent Off": "请填写中文",
    "Race to the 3rd corner?": "请填写中文",
    "Race to the 5th corner?": "请填写中文",
    "Race to the 7th corner?": "请填写中文",
    "Race to the 9th corner?": "请填写中文",
    "Result / Both Teams To Score": "请填写中文",
    "Sudden Death": "请填写中文",
    "To Qualify": "请填写中文",
    "To Score 2 or More": "请填写中文",
    "To Score 3 or More": "请填写中文",
    "To Win 2nd Half": "请填写中文",
    "Total Cards": "请填写中文",
    "Total Converted Penalties": "请填写中文",
    "Total Corners": "请填写中文",
    "Total Corners (3 way) (1st Half)": "请填写中文",
    "Total Corners (3way) (2nd Half)": "请填写中文",
    "Total Penalties in Shootout": "请填写中文",
    "Total Shots": "请填写中文",
    "Total shots on goal": "请填写中文",
    "Which team will score the 1st goal?": "请填写中文",
    "Which team will score the 2nd goal in extra time?": "请填写中文",
    "Which team will score the 2nd goal?": "请填写中文",
    "Which team will score the 3rd goal?": "请填写中文",
    "Which team will score the 4th goal?": "请填写中文",
    "Which team will score the 5th goal?": "请填写中文",
    "Which team will score the 6th goal?": "请填写中文",
    "Which team will score the 7th goal?": "请填写中文",
    "Which team will score the 8th goal?": "请填写中文",
})
